import type { Metadata } from 'next';
import { Noto_Sans_JP } from 'next/font/google';
import './globals.css';
import AppProvider from '@/provider/AppProvider';

const notoSansJP = Noto_Sans_JP({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="ja">
			<body className={`${notoSansJP.className} text-zinc-50`}>
				<div className="relative">
					<div className="absolute inset-0 bg-black opacity-60 z-10"></div>
					<div className="h-[100vh] bg-[url('/img/blockchain.jpg')] bg-center bg-cover bg-opacity-80"></div>
					<div className="absolute inset-0 bg-transparent z-20 container">
						<AppProvider>{children}</AppProvider>
					</div>
				</div>
			</body>
		</html>
	);
}
